env:
  dense_reward_scale: 0.2
  frame_skip: 2
  action_type: multi_discrete
  observation_type: pixels

env_size:
  num_polygons: 5
  num_circles: 2
  num_joints: 1
  num_thrusters: 1
  env_size_name: s
  num_motor_bindings: 4
  num_thruster_bindings: 2
  env_size_type: predefined

learning:
  lr: 5e-05
  peak_lr: 0.0003
  initial_lr: 1e-05
  warmup_frac: 0.1
  max_grad_norm: 1.0
  total_timesteps: 1073741824
  num_train_envs: 2048
  num_minibatches: 32
  gamma: 0.995
  update_epochs: 8
  clip_eps: 0.2
  gae_lambda: 0.9
  ent_coef: 0.01
  anneal_lr: false
  warmup_lr: false
  vf_coef: 0.5
  permute_state_during_training: false
  filter_levels: true
  level_filter_n_steps: 64
  level_filter_sample_ratio: 2
  num_steps: 64
  num_repeats: 1

misc:
  group: auto
  group_auto_prefix: ""
  save_path: checkpoints/kinetix
  use_wandb: true
  save_policy: true
  wandb_project: null
  wandb_entity: null
  wandb_mode: online
  video_frequency: 2
  load_from_checkpoint: null
  load_only_params: true
  checkpoint_save_freq: 512
  checkpoint_human_numbers: false
  economical_saving: false
  log_buffer_freq: []

eval:
  eval_levels:
    - s/h0_weak_thrust
    - s/h7_unicycle_left
    - s/h3_point_the_thruster
    - s/h4_thrust_aim
    - s/h1_thrust_over_ball
    - s/h5_rotate_fall
    - s/h9_explode_then_thrust_over
    - s/h6_unicycle_right
    - s/h8_unicycle_balance
    - s/h2_one_wheel_car
  eval_num_attempts: 20
  eval_freq: 64
  EVAL_ON_SAMPLED: true

train_levels:
  train_level_mode: list
  train_levels_list:
    - s/h0_weak_thrust
    - s/h7_unicycle_left
    - s/h3_point_the_thruster
    - s/h4_thrust_aim
    - s/h1_thrust_over_ball
    - s/h5_rotate_fall
    - s/h9_explode_then_thrust_over
    - s/h6_unicycle_right
    - s/h8_unicycle_balance
    - s/h2_one_wheel_car

model:
  fc_layer_depth: 5
  fc_layer_width: 128
  activation: tanh
  recurrent_model: false
  transformer_depth: 2
  transformer_size: 16
  transformer_encoder_size: 128
  num_heads: 8
  full_attention_mask: false
  aggregate_mode: dummy_and_mean
  symbolic_embedding_dim: 256
  encoder_size: 64
  permutation_invariant_mlp: false
